server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 30GB
  #      file-size-threshold: 3MB

  cloud:
    gateway:
      routes:
        - id: upload-service
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/upload-api/upload
            - Method=POST
          filters:
            - SetPath=/api/upload
debug: true
